export const field = [

  { id: 'A',
    value: [{ id: 'A1', team: 1 },
            { id: 'A2', team: 2 },
            { id: 'A3', team: null },
            { id: 'A4', team: null },
            { id: 'A5', team: null },
            { id: 'A6', team: null },
            { id: 'A7', team: null },
            { id: 'A8', team: null }]
  },
  { id: 'B',
    value: [{ id: 'B1', team: null },
            { id: 'B2', team: null },
            { id: 'B3', team: null },
            { id: 'B4', team: null },
            { id: 'B5', team: null },
            { id: 'B6', team: null },
            { id: 'B7', team: null },
            { id: 'B8', team: null }]
  },
  { id: 'C',
    value: [{ id: 'C1', team: null },
            { id: 'C2', team: null },
            { id: 'C3', team: null },
            { id: 'C4', team: null },
            { id: 'C5', team: null },
            { id: 'C6', team: null },
            { id: 'C7', team: null },
            { id: 'C8', team: null }]
  },
  { id: 'D',
    value: [{ id: 'D1', team: null },
            { id: 'D2', team: null },
            { id: 'D3', team: null },
            { id: 'D4', team: null },
            { id: 'D5', team: null },
            { id: 'D6', team: null },
            { id: 'D7', team: null },
            { id: 'D8', team: null }]
  },
  { id: 'E',
    value: [{ id: 'E1', team: null },
            { id: 'E2', team: null },
            { id: 'E3', team: null },
            { id: 'E4', team: null },
            { id: 'E5', team: null },
            { id: 'E6', team: null },
            { id: 'E7', team: null },
            { id: 'E8', team: null }]
  },
  { id: 'F',
    value: [{ id: 'F1', team: null },
            { id: 'F2', team: null },
            { id: 'F3', team: null },
            { id: 'F4', team: null },
            { id: 'F5', team: null },
            { id: 'F6', team: null },
            { id: 'F7', team: null },
            { id: 'F8', team: null }]
  },
  { id: 'F',
    value: [{ id: 'G1', team: null },
            { id: 'G2', team: null },
            { id: 'G3', team: null },
            { id: 'G4', team: null },
            { id: 'G5', team: null },
            { id: 'G6', team: null },
            { id: 'G7', team: null },
            { id: 'G8', team: null }]
  },
  { id: 'F',
    value: [{ id: 'H1', team: null },
            { id: 'H2', team: null },
            { id: 'H3', team: null },
            { id: 'H4', team: null },
            { id: 'H5', team: null },
            { id: 'H6', team: null },
            { id: 'H7', team: null },
            { id: 'H8', team: null }]
  }
];
